#!/bin/bash

klienti=( bubokrki paulinia m jedejedemasinka okno MAGA nahodicka buj nulano niekto )
mapy=( mapy/*.ppm )
nazvy=(
  'niekto'
  'BUBOKRKI'
  'nulano'
  'buj'
  'nahodicka'
  'MAGA'
  'Windows Vista'
  'Jedejedemasinka'
  'Makroωlnky'
  'paulinia'
)

for mapa in ${mapy[@]}; do
  echo "spustam hru na mape $mapa"

  buildy=()
  for klient in "${klienti[@]}"; do
    najnovsi=`ls hlavnykomp/buildy/$klient/*/.status.ok 2>/dev/null | tail -n1`
    [ -z "$najnovsi" ] && echo "klient $klient nema ziaden ok build!" && continue 
    buildy+=("${najnovsi%/*}")
  done
  buildystr="${buildy[*]}"
  buildystr="${buildystr//"hlavnykomp/buildy/"}"
  echo "klienti: $buildystr"
  
  # $((...)) konvertuje 010 na 8, expr nie
  # ta 0 navyse je pre pripad ze zaznamy/ su prazdne
  dir=$(expr "0$(ls zaznamy/ | grep -Eo '^[0-9]{6}' | tail -n1)" + 1)
  dir=zaznamy/`printf '%06d' "$dir"`
  mkdir $dir
  echo "adresar: $dir"

  echo "clients=${buildystr// /,}
server=`stat -c %Y server/server`
map=$mapa
begin=`date +%s`
state=playing" > $dir.manifest
  for (( i = 0; i < ${#klienti[@]}; i++ )); do
    echo "${klienti[$i]}"
    echo "${buildy[$i]##*/}"
    echo "${nazvy[$i]}"
  done > $dir/titles

  if ./server/server $dir $mapa ${buildy[@]} &>$dir/stderr.srv; then
    rank=`tail $dir/rank`
    echo "hotovo"
    echo "rank=${rank//$'\n'/,}" >> $dir.manifest
    sed -i 's/^state=.*/state=displaying/' $dir.manifest    
    bash hlavnykomp/gen-ranklist > $dir.ranklist
  else
    exitcode=$?
    echo "server spadol s kodom $?"
    echo "exitcode=$exitcode" >> $dir.manifest
    sed -i 's/^state=.*/state=crashed/' $dir.manifest
    sleep 10
  fi
done
