#!/usr/bin/env python

import sys
import os

fo = open(sys.argv[1]+"/color", "r")
lines_list = fo.readlines()
fo.close()
s='set term png enhanced\n'\
'set output "graph.png"\n'\
'set key opaque\n'\
'scale(x)=x*255\n'\
'rgb(r,g,b) = int(scale(r))*65536 + int(scale(g))*256 + int(scale(b))\n'\
'plot \\\n'
for i in range(len(lines_list)):
    farba=lines_list[-(i+1) ].split()
    s=s+'    "graph" using 1:('
    for j in range(len(lines_list)-i):
        if j>0: s=s+'+'
        s=s+'$'+str(j+2)
    s=s+'):(rgb('+str(farba[0])+','+str(farba[1])+','+str(farba[2])+')) title columnheader('+str(len(lines_list)-i+1)+') with filledcurves x1 lt rgb variable, \\\n'
fo=open(sys.argv[1]+"/gnuplot.gnu", "w")
fo.write(s)
fo.close()
os.system('cd '+sys.argv[1]+'; gnuplot gnuplot.gnu;')
